Repository NTBBloodbath/doom-nvim, pull requests merged in 2021-09, with the labels that each got.

#114 fix: replace deprecated values for dap-ui
  lua/doom/modules/config/doom-dap-ui.lua
Labels: branch: main, plugins: breaking changes

#115 neorg now has an org, replaced links for them
  lua/doom/modules/config/doom-treesitter.lua
  lua/doom/modules/init.lua
Labels: enhancement, branch: main

#122 fix(modules): update gitsigns configuration
  lua/doom/modules/config/doom-gitsigns.lua
Labels: branch: main, plugins: breaking changes

#128 docs: correct description (split or not)
  lua/doom/extras/keybindings/init.lua
Labels: documentation, branch: main

#137 fix(dapui): open_on_start deprecated
  lua/doom/modules/config/doom-dap-ui.lua
Labels: plugins: breaking changes

#141 feat(gitignore): ignore editor artifacts
  .gitignore
Labels: enhancement

#140 Drop a line from DOOM logo
  lua/doom/modules/config/doom-dashboard.lua
Labels: enhancement, branch: develop

#139 modeline by nvim 0.5 is as secure
  doom_config.lua
Labels: enhancement, branch: develop

#143 fix(gitsigns) match new variable name
  lua/doom/modules/config/doom-gitsigns.lua
Labels: branch: develop, plugins: breaking changes

#146 fix(modules): correct usage of config property
  lua/doom/modules/config/doom-tree.lua
Labels: enhancement, branch: main
