Repository NTBBloodbath/doom-nvim, pull requests merged in 2021-07, with the labels that each got.

#28 use /usr/bin/env bash to make install more portable
  install.sh
Labels: enhancement

#62 Add options to doom_config (#60)
  doom_config.lua
  lua/doom/core/default/init.lua
  lua/doom/core/functions/init.lua
Labels: branch: develop, enhancement

#63 Hotfix for #60
  lua/doom/core/default/init.lua
Labels: branch: develop

#66 merge: docs/getting-started
  docs/getting_started.md
Labels: documentation
