Repository NTBBloodbath/doom-nvim, pull requests merged in 2021-11, with the labels that each got.

#229 feat(mappings): user defind esc sequences
  doom_config.lua
  lua/doom/core/config/init.lua
  lua/doom/extras/keybindings/core.lua
Labels: enhancement, branch: develop

#231 Docs/windows install
  docs/getting_started.md
Labels: documentation, enhancement

#248 Fixed :DoomReport not collecting logs
  lua/doom/core/functions/init.lua
Labels: scope: enhancement
